build-dhcom-hal-arm32v7:
  image: $CI_REGISTRY/docker-images/debian-build-essential:buster-arm32v7
  stage: build
  script:
    - uname -m
    - apt-get --no-install-recommends -y install file git libgpiod-dev
    - mkdir build
    - cd build
    - cmake CMakeLists.txt ../
    - make
    - cpack
    - mv *.deb ../
  artifacts:
    paths:
      - libdhcom-hal*.deb

build-dhcom-hal-arm32v5:
  # override default image
  image: $CI_REGISTRY/docker-images/debian-build-essential:buster-arm32v5
  stage: build
  script:
    - uname -m
    - apt-get --no-install-recommends -y install file git libgpiod-dev
    - mkdir build
    - cd build
    - cmake CMakeLists.txt ../
    - make
    - cpack
    - mv *.deb ../
  artifacts:
    paths:
      - libdhcom-hal*.deb

